### ISSUE TITLE
add pagination to author get endpoint

### ISSUE THREAD

**Issue by jeffreybakker** [kickin-media/media-back-end#15]
In order to limit response times for authors with a lot of uploads (and/or multiple events). With ie `limit=50` & `offset=0` query params

**Comment by jonathanjuursema** [comment]
I think the author photos were in the author endpoint more or less by accident, and from what I could tell you're not using them yet, so I've moved the photos of a particular author to a new endpoint (`/author/<id>/photos`) with a `page` query param and a page size of 50. :)
